apiVersion: meta.dev.upbound.io/v1alpha1
kind: Project
metadata:
  name: addon-argocd-core
spec:
  description: addon-argocd-core
  license: Apache-2.0
  maintainer: Upbound Maintainers <info@upbound.io>
  readme: |
    Test for addon-argocd-core
  repository: xpkg.upbound.io/upbound/addon-argocd-core_test
  source: github.com/upbound/addon-argocd-core
