name: publish-image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - 'mkdocs.yml'
jobs:
  call-publish-image:
    name: Publish Image
    runs-on: ubuntu-latest
    environment: Dagger build env
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Upbound Marketplace
        uses: docker/login-action@v2
        with:
          registry: xpkg.upbound.io
          username: ${{ secrets.XPKG_ACCESS_ID }}
          password: ${{ secrets.XPKG_ACCESS_TOKEN }}
      - name: Install up cli
        uses: upbound/action-up@v1
        with:
          api-token: ${{ secrets.UP_API_TOKEN }}
          organization: upbound-demo
      - name: Build and Publish
        env:
          UPBOUND_API_TOKEN: ${{ secrets.UP_API_TOKEN }}
          UPBOUND_ACCOUNT: upbound-demo
          UPBOUND_REPO: upbound-demo
        run: |
          source .chart-attributes
          helm pull $CHART_NAME --repo $REPO_URL --version $CHART_VERSION
          mkdir helm
          mv $CHART_NAME-$CHART_VERSION.tgz helm/chart.tgz
          mkdir crds
          helm template $RELEASE_NAME helm/chart.tgz -n $RELEASE_NAME --include-crds | \\n  yq e 'select(.kind == "CustomResourceDefinition")' - | \\n  yq -s '("crds/" + .metadata.name + ".yaml")' -
          up xpkg build

          export CONTROLLER_NAME=$(printf '%s' "$GITHUB_REPOSITORY" | sed 's/.*\///')

          up xpkg push xpkg.upbound.io/$UPBOUND_ACCOUNT/$CONTROLLER_NAME:$CHART_VERSION -f $XPKG_FILENAME
